server:
  port: ${APP_PORT:8891}
  servlet:
    context-path: /graduation
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false}
    username: ${DATABASE_USERNAME:postgres.jmojdxyjbqqmswgvbekb}
    password: ${DATABASE_PASSWORD:ytOtrx9OfBuZOLXT}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: graduation
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      # modify fetch size as necessary
      hibernate.jdbc.fetch_size: 200
      hibernate.criteria.literal_handling_mode: BIND
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.jdbc.lob.non_contextual_creation: true
